export const LANGUAGE_MAPPING: Record<AvailableLanguage, string> = {
    orm: "Afaan Oromoo",
    afr: "Afrikaans",
    ase: "American Sign Language (ASL)",
    apw: "Apache",
    asf: "Auslan",
    aym: "Aymar Aru",
    ind: "Bahasa Indonesia",
    msa: "Bahasa Melayu",
    bam: "Bambara",
    tzo: "Bats'i k'op",
    bik: "Bikol",
    bis: "Bislama",
    cak: "Cakchiquel",
    cat: "Català",
    ceb: "Cebuano",
    ces: "Česky",
    cha: "Chamoru",
    nya: "Chichewa",
    cym: "Cymraeg",
    dan: "Dansk",
    deu: "Deutsch",
    nav: "Diné bizaad",
    cuk: "Dulegaya",
    yor: "Èdè Yorùbá",
    est: "Eesti",
    efi: "Efik",
    guz: "EkeGusii",
    eng: "English",
    spa: "Español",
    eus: "Euskera",
    ton: "Faka-tonga",
    fat: "Fante",
    hif: "Fiji Hindi",
    chk: "Fosun Chuuk",
    fon: "Fɔngbè",
    fra: "Français",
    smo: "Gagana Samoa",
    tvl: "gana Tuvalu",
    grn: "Guaraní (Avañe'ẽ)",
    hil: "Hiligaynon",
    hmo: "Hiri Motu",
    hmn: "Hmoob",
    hrv: "Hrvatski",
    haw: "ʻŌlelo Hawaiʻi",
    sto: "I^ethka (Yethka)",
    ibo: "Igbo",
    ilo: "Ilokano",
    nbl: "isiNdebele",
    xho: "isiXhosa",
    zul: "isiZulu",
    isl: "Íslenska",
    ita: "Italiano",
    kos: "Kahs Kosrae",
    mah: "Kajin Majōl",
    qvi: "Kichwa",
    kam: "Kikamba",
    kin: "Kinyarwanda",
    gil: "Kiribati",
    swa: "Kiswahili",
    niu: "ko e vagahau Niuē",
    hat: "Kreyòl Ayisyen",
    lav: "Latviešu",
    lit: "Lietuvių",
    lin: "Lingála",
    yua: "maayaʼ tʼàan",
    hun: "Magyar",
    pon: "Mahsen en Pohnpei",
    mlg: "Malagasy",
    mlt: "Malti",
    mam: "Mam",
    rar: "Māori Kuki Airani",
    nld: "Nederlands",
    bla: "Nitsi’powahsin",
    cag: "Nivacle",
    nor: "Norsk",
    pau: "Palauan",
    pam: "Pampango",
    pag: "Pangasinan",
    pap: "Papiamento",
    pol: "Polski",
    por: "Português (Brasil)",
    ept: "Português (Portugal)",
    kek: "Q'eqchi'",
    quh: "Quechua-Bolivia",
    quc: "Quiché",
    tah: "Reo Tahiti",
    ron: "Română",
    nso: "sePêdi",
    tsn: "Setswana",
    sna: "Shona",
    alb: "Shqip",
    ssw: "siSwati",
    slk: "Slovenčina",
    slv: "Slovenščina",
    sot: "South Sotho",
    fin: "Suomi",
    swe: "Svenska",
    tgl: "Tagalog",
    mri: "Te Reo Māori",
    yap: "Thin Nu Wa'ab",
    vie: "Tiếng Việt",
    tpi: "Tok Pisin",
    lua: "Tshiluba",
    tur: "Türkçe",
    twi: "Twi",
    fij: "Vosa vakaviti",
    war: "Waray",
    quz: "Yunkay Quechua",
    ell: "Ελληνικά",
    bul: "Български",
    kaz: "Қазақ",
    mkd: "Македонски",
    mon: "Монгол",
    rus: "Русский",
    srp: "Српски",
    ukr: "Українська",
    kat: "ქართული",
    hyw: "Արեւմտահայերէն",
    hye: "Հայերեն",
    urd: "اردو",
    ara: "العربية",
    pes: "فارسی",
    amh: "አማርኛ",
    nep: "नेपाली",
    hin: "हिन्दी, हिंदी",
    ben: "বাংলা",
    tam: "தமிழ்",
    tel: "తెలుగు",
    kan: "ಕನ್ನಡ",
    sin: "සිංහල",
    tha: "ภาษาไทย",
    lao: "ພາສາລາວ",
    ksw: "ကညီလံာ်ခီၣ်ထံ",
    mya: "ဗမာစာ",
    khm: "ភាសាខ្មែរ",
    kor: "한국어",
    jpn: "日本語",
    zhs: "简体中文 - 普通话",
    zho: "繁體中文 - 國語",
    yue: "繁體中文 - 廣東話",
} as const;

export const AVAILABLE_LANGUAGES = [
    "orm",
    "afr",
    "ase",
    "apw",
    "asf",
    "aym",
    "ind",
    "msa",
    "bam",
    "tzo",
    "bik",
    "bis",
    "cak",
    "cat",
    "ceb",
    "ces",
    "cha",
    "nya",
    "cym",
    "dan",
    "deu",
    "nav",
    "cuk",
    "yor",
    "est",
    "efi",
    "guz",
    "eng",
    "spa",
    "eus",
    "ton",
    "fat",
    "hif",
    "chk",
    "fon",
    "fra",
    "smo",
    "tvl",
    "grn",
    "hil",
    "hmo",
    "hmn",
    "hrv",
    "haw",
    "sto",
    "ibo",
    "ilo",
    "nbl",
    "xho",
    "zul",
    "isl",
    "ita",
    "kos",
    "mah",
    "qvi",
    "kam",
    "kin",
    "gil",
    "swa",
    "niu",
    "hat",
    "lav",
    "lit",
    "lin",
    "yua",
    "hun",
    "pon",
    "mlg",
    "mlt",
    "mam",
    "rar",
    "nld",
    "bla",
    "cag",
    "nor",
    "pau",
    "pam",
    "pag",
    "pap",
    "pol",
    "por",
    "ept",
    "kek",
    "quh",
    "quc",
    "tah",
    "ron",
    "nso",
    "tsn",
    "sna",
    "alb",
    "ssw",
    "slk",
    "slv",
    "sot",
    "fin",
    "swe",
    "tgl",
    "mri",
    "yap",
    "vie",
    "tpi",
    "lua",
    "tur",
    "twi",
    "fij",
    "war",
    "quz",
    "ell",
    "bul",
    "kaz",
    "mkd",
    "mon",
    "rus",
    "srp",
    "ukr",
    "kat",
    "hyw",
    "hye",
    "urd",
    "ara",
    "pes",
    "amh",
    "nep",
    "hin",
    "ben",
    "tam",
    "tel",
    "kan",
    "sin",
    "tha",
    "lao",
    "ksw",
    "mya",
    "khm",
    "kor",
    "jpn",
    "zhs",
    "zho",
    "yue",
] as const;

export type AvailableLanguage = (typeof AVAILABLE_LANGUAGES)[number];

export const BOOK_ABBREVIATION_MAPPING: Record<
    AvailableLanguage,
    Map<string, string> | null
> = {
    orm: null,
    afr: null,
    ase: null,
    apw: null,
    asf: null,
    aym: null,
    ind: null,
    msa: null,
    bam: null,
    tzo: null,
    bik: null,
    bis: null,
    cak: null,
    cat: null,
    ceb: null,
    ces: null,
    cha: null,
    nya: null,
    cym: null,
    dan: null,
    deu: null,
    nav: null,
    cuk: null,
    yor: null,
    est: null,
    efi: null,
    guz: null,
    eng: new Map([
        ["d&c", "Doctrine and Covenants"],
        ["dc", "Doctrine and Covenants"],
        ["jsh", "Joseph Smith History"],
        ["js-h", "Joseph Smith History"],
        ["jsm", "Joseph Smith Matthew"],
        ["js-m", "Joseph Smith Matthew"],
    ]),
    spa: new Map([["dyc", "Doctrina y Convenios"]]),
    eus: null,
    ton: null,
    fat: null,
    hif: null,
    chk: null,
    fon: null,
    fra: null,
    smo: null,
    tvl: null,
    grn: null,
    hil: null,
    hmo: null,
    hmn: null,
    hrv: null,
    haw: null,
    sto: null,
    ibo: null,
    ilo: null,
    nbl: null,
    xho: null,
    zul: null,
    isl: null,
    ita: null,
    kos: null,
    mah: null,
    qvi: null,
    kam: null,
    kin: null,
    gil: null,
    swa: null,
    niu: null,
    hat: null,
    lav: null,
    lit: null,
    lin: null,
    yua: null,
    hun: null,
    pon: null,
    mlg: null,
    mlt: null,
    mam: null,
    rar: null,
    nld: null,
    bla: null,
    cag: null,
    nor: null,
    pau: null,
    pam: null,
    pag: null,
    pap: null,
    pol: null,
    por: null,
    ept: null,
    kek: null,
    quh: null,
    quc: null,
    tah: null,
    ron: null,
    nso: null,
    tsn: null,
    sna: null,
    alb: null,
    ssw: null,
    slk: null,
    slv: null,
    sot: null,
    fin: null,
    swe: null,
    tgl: null,
    mri: null,
    yap: null,
    vie: null,
    tpi: null,
    lua: null,
    tur: null,
    twi: null,
    fij: null,
    war: null,
    quz: null,
    ell: null,
    bul: null,
    kaz: null,
    mkd: null,
    mon: null,
    rus: null,
    srp: null,
    ukr: null,
    kat: null,
    hyw: null,
    hye: null,
    urd: null,
    ara: null,
    pes: null,
    amh: null,
    nep: null,
    hin: null,
    ben: null,
    tam: null,
    tel: null,
    kan: null,
    sin: null,
    tha: null,
    lao: null,
    ksw: null,
    mya: null,
    khm: null,
    kor: null,
    jpn: null,
    zhs: null,
    zho: null,
    yue: null,
};
