name: Release Obsidian plugin

on:
    release:
        types: [ created ]

env:
    PLUGIN_NAME: lds-scriptures-reference

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Build
                id: build
                run: |
                    npm install
                    npm run build
                    ls
                    echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
            -   name: Upload main.js
                id: upload-main
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./main.js
                    asset_name: main.js
                    asset_content_type: text/javascript

            -   name: Upload manifest.json
                id: upload-manifest
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./manifest.json
                    asset_name: manifest.json
                    asset_content_type: application/json

            -   name: Upload styles.css
                id: upload-css
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./styles.css
                    asset_name: styles.css
                    asset_content_type: text/css
